# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow - untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def real(self):
        print("sucsess")
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menumenu = QtWidgets.QMenu(self.menubar)
        self.menumenu.setObjectName("menumenu")
        self.menuekle = QtWidgets.QMenu(self.menubar)
        self.menuekle.setObjectName("menuekle")
        self.menusil = QtWidgets.QMenu(self.menubar)
        self.menusil.setObjectName("menusil")
        self.menulistele = QtWidgets.QMenu(self.menubar)
        self.menulistele.setObjectName("menulistele")
        self.menuekle_2 = QtWidgets.QMenu(self.menubar)
        self.menuekle_2.setObjectName("menuekle_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionmenusecim = QtWidgets.QAction(MainWindow)
        self.actionmenusecim.setObjectName("actionmenusecim")
        self.actionekle = QtWidgets.QAction(MainWindow)
        self.actionekle.setObjectName("actionekle")
        self.actionsil = QtWidgets.QAction(MainWindow)
        self.actionsil.setCheckable(False)
        self.actionsil.setChecked(False)
        self.actionsil.setObjectName("actionsil")
        self.menumenu.addAction(self.actionmenusecim)
        self.menuekle.addAction(self.actionekle)
        self.menusil.addAction(self.actionsil)
        self.menubar.addAction(self.menumenu.menuAction())
        self.menubar.addAction(self.menuekle.menuAction())
        self.menubar.addAction(self.menusil.menuAction())
        self.menubar.addAction(self.menulistele.menuAction())
        self.menubar.addAction(self.menuekle_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menumenu.setTitle(_translate("MainWindow", "menu"))
        self.menuekle.setTitle(_translate("MainWindow", "ekle"))
        self.menusil.setTitle(_translate("MainWindow", "sil"))
        self.menulistele.setTitle(_translate("MainWindow", "listele"))
        self.menuekle_2.setTitle(_translate("MainWindow", "ekle"))
        self.actionmenusecim.setText(_translate("MainWindow", "menusecim"))
        self.actionekle.setText(_translate("MainWindow", "ekle"))
        self.actionsil.setText(_translate("MainWindow", "sil"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())